### ISSUE TITLE
how mature is this project?

### ISSUE THREAD

**Issue by ericremoreynolds** [mathnet/mathnet-linqalgebra#2]
Hello,

I would like to do some symbolic algebra in C# (automatic differentiation etc.) and I am deciding whether to write my own library or use this one (I have not found many other serious symbolic algebra libraries in C#).

My only doubt is that, seeing that the project has been inactive for 5 years, how mature/stable/functional is it?

Thanks, regards,

Eric.

**Comment by ericremoreynolds** [comment]
I have just seen the Math.NET symbolics project maybe that is what I should use.

**Comment by cdrnet** [comment]
Yes, mathnet/mathnet-symbolics is much more mature despite being written in just a few days. But while still being .Net it is written in F# instead of C#.

**Comment by cdrnet** [comment]
There have actually been quite a few takes at basic computer algebra within Math.NET:
- The original Math.NET (classic) library back from ~2002 was fairly mature and could even do symbolic linear algebra (i.e. solving linear equation systems symbolically), but it was very complicated in design mostly due to lacking experience on my side.
- Math.NET Yttrium is purely experimental (with a symbolic graph approach instead of trees). Do not use.
- Math.NET Linq Algebra is quite basic but could be extended. It could also serve as a starting point for your project if using Linq expression is interesting to your case. However, writing something like this in C# requires a lot of ceremony.
- Math.NET Symbolics is written in F# (.Net 4.5) and already much more mature despite the least amount of code by far. This is the one I'll continue to invest time into to extend it further.

**Comment by ericremoreynolds** [comment]
Christoph,

Ok I will try Symbolics. My use case is automatic differentiation. While I have your attention, if I may I'd like to ask you a couple more questions:

1) Is there any history of using it from C#?
2) Does it support compilation of expressions to IL code?

Thanks for your help and for the libraries,

Eric.

**Comment by cdrnet** [comment]
1) No, and it is indeed not well suited to be used from C# directly right now. I actually have thought about usage from C# and VB.net and so far concluded that it would make sense to create an `Expression` class that carries an expression tree internally but provides all the functionality through methods and operators as you'd expect from C#.

2) No, not yet
